### ISSUE TITLE
share trained networks

### ISSUE THREAD

**Issue by saleknia** [HiLab-git/WORD#1]
Hi
I'm really in need of a neural network which has been trained on your dataset, but as result of lack of appropriate hardware resource its impossible for me to do it. Is it possible for you to share few models that you have trained in your paper?

**Comment by Luoxd1996** [comment]
Hi,
We will provide a pre-trained model and inference pipeline later.
Best,
Xiangde.

**Comment by Luoxd1996** [comment]
Hi,
I have shared the pre-trained nnUNet3DV2 model with you, you can use it for testing now; the google drive download link at: https://drive.google.com/file/d/17NxupmGj0E8y0nLTNSUXzUQIOzqOlNbM/view?usp=sharing, the inference pipeline you can use the original nnUNet(https://github.com/MIC-DKFZ/nnUNet) or we modified nnunet_mini(https://github.com/Luoxd1996/nnunet_mini/blob/main/Inference3D.py).
Best,
Xiangde.

**Comment by saleknia** [comment]
Thank you for your attention and excuse me for a long delay. Although the checkpoints you have shared are really precious, I'm especially in need of 2D pre-trained models. Is it possible for you to also share them?
