### ISSUE TITLE
share pre-trained 2D network

### ISSUE THREAD

**Issue by saleknia** [HiLab-git/WORD#2]
Hi
In the another issue I asked for pre-trained networks, that you generously shared pre-trained nnUNet3DV2 model with me. Is it possible for you to also share a 2D pre-trained model?

**Comment by Luoxd1996** [comment]
Hi,
This is the trained nnUNet2DV2: https://drive.google.com/file/d/1tgcV_PuV70hgKmiVUxxPVnoQKeuqqjxe/view?usp=sharing .
Best,
Xiangde.
