### ISSUE TITLE
Threshold interception in the preprocessing process

### ISSUE THREAD

**Issue by smallkaka** [HiLab-git/WORD#3]
Hello, thank you for your valuable work. I want to use your data set to train the segmentation model. I want to use threshold interception in the preprocessing process. I wonder if you know how much the most suitable threshold should be selected?

**Comment by Luoxd1996** [comment]
Hi,
I don't know what is your datasets' modality CT (should use a fixed window and level ) or MRI (can use the intensity histogram 0.5%~99.5%).
Best regards,
Xiangde Luo.

**Comment by smallkaka** [comment]
It is Word datasets.I would like to know the most appropriate truncation threshold for the Word dataset, if you know it.

**Comment by Luoxd1996** [comment]
Hi,
Yes, I would like to recommend you use the fixed HU range [-125, 275] to cut off the intensity. For example:
` image[image <=-125] = -125`
` image[image >= 275] = 275`
Best regard,
Xiangde Luo.

**Comment by smallkaka** [comment]
This is very helpful for me, thank you very much for your reply.
