### ISSUE TITLE
can't reproduce the segmentation results of left femoral head and right femoral head

### ISSUE THREAD

**Issue by Ctozzzzz** [HiLab-git/WORD#4]
I've tried training both 2D nnUNetv2 and  3D nnUNetv2 using the WORD dataset. But I found that the segmentation results of  Head of femur were not as good as illustrated in the paper. The result of 3D nnUNetv2 were:
| target           | DSC         | HD95           |
| ---------------- | ----------- | -------------- |
| Head of femur(L) | 0.545±0.114 | 196.485±22.436 |
| Head of femur(R) | 0.471±0.138 | 173.113±35.954 | 

If you have met this situation, I wonder if you can offer me an explanation or guideline. Thank you😀

**Comment by Luoxd1996** [comment]
Hi, 
It is caused by the flipping augmentation, there are two solutions: turn off the flipping augmentation or post-processing.
Best,
Xiangde Luo.

**Comment by Ctozzzzz** [comment]
> Hi, It is caused by the flipping augmentation, there are two solutions: turn off the flipping augmentation or post-processing. Best, Xiangde Luo.

I will try it. Thank you so much!
