### ISSUE TITLE
Did you use 5F-CV for evaluation?

### ISSUE THREAD

**Issue by Karol-G** [HiLab-git/WORD#9]
Hey,

Did you use five-fold cross-validation during the evaluation in the WORD paper? You only mention that you use the default settings and 5F-CV is part of the default settings, but I want to be sure.

Best,
Karol

**Comment by Luoxd1996** [comment]
Hi,
No, we don't use the 5-fold evaluation, where we split the dataset into
three parts, training, validation and testing.
Best,
Xiangde.

Karol Gotkowski ***@***.***> 于2024年2月26日周一 21:20写道：

**Comment by Karol-G** [comment]
Hey,

Thank you for your answer! Could you please provide your used dataset split files so I know which images have been used for training, validation, and testing?

Best,
Karol

**Comment by Luoxd1996** [comment]
Hi,
We have split the dataset into three parts, imagesTr, imagesVal and
imagesTs mean the training, validation and testing sets images, and their
label folds are labelsXXX, the labelsTs is provided in the github
repository.
Best,
Xiangde Luo.

Karol Gotkowski ***@***.***> 于2024年2月29日周四 21:12写道：

**Comment by Karol-G** [comment]
Hey, 

Thank you. I noticed it the moment I wrote this issue >.<

Best,
Karol
